[NCLSUP-959] Fix DirectoryNotEmptyException: /tmp/vfs_cache
We've seen following error:

```
java.lang.RuntimeException: Failed to analyze checksums
 at org.jboss.pnc.deliverablesanalyzer.Finder.find(Finder.java:236)
 at org.jboss.pnc.deliverablesanalyzer.Finder.lambda$find$0(Finder.java:133)
 at io.smallrye.context.impl.wrappers.SlowContextualCallable.call(SlowContextualCallable.java:21)
 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
 at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
 at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
 at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
 at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.nio.file.DirectoryNotEmptyException: /tmp/vfs_cache
 at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:247)
 at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
 at java.base/java.nio.file.Files.deleteIfExists(Files.java:1181)
 at org.jboss.pnc.build.finder.core.DistributionAnalyzer.cleanupVfsCache(DistributionAnalyzer.java:293)
 at org.jboss.pnc.build.finder.core.DistributionAnalyzer.checksumFiles(DistributionAnalyzer.java:264)
 at org.jboss.pnc.build.finder.core.DistributionAnalyzer.call(DistributionAnalyzer.java:568)
 at org.jboss.pnc.deliverablesanalyzer.Finder.find(Finder.java:234) ... 10 more
```

This change makes the cleanupVfsCache method delete the folder
recursively